<?php
    $GLOBALS['regex_array'] = array(
        'nom'           => "#^[a-zA-ZаюбдихйкмлносртжзышэАЮБДИХЙКМЛНОСРТЖЗЫШЭгГ\- ()'`]{0,}$#",
        'jeune_fille'   => "#^[a-zA-ZаюбдихйкмлносртжзышэАЮБДИХЙКМЛНОСРТЖЗЫШЭгГ\- `]{0,}$#",
        'date'          => "#^\d{4}\-\d{2}\-\d{2}$#",
        'telephone'     => "#^0[1-589]([-. ]?\d{2}){4}$#",
        'portable'      => "#^0[67]([-. ]?[0-9]{2}){4}$#",
        'nombre'        => "#^\d+(\.\d+)|\d+$#",
        'mail'          => "#^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$#",
        'mnemonique'    => "#^[A-Z]{3}$#",
        'majuscule'     => "#^[A-Zаюбдихйкмлносртжзышэг]#",
        'nss'           => "#^[1|2|8]\d{14}$#",
        'adresse'       => "#^[0-9A-Za-zаюбдихйкмлносртжзышэАЮБДИХЙКМЛНОСРТЖЗЫШЭгГ\- `]{0,}$#",
        'no_compte'     => "#^[A-Z0-9]{11}$#",
        'commentaire'   => "#^[0-9A-Za-zаюбдихйкмлносртжзышэАЮБДИХЙКМЛНОСРТЖЗЫШЭгГ\- ,;:.!?`]{0,}$#",
        'cp'            => "#^\d{5}$#",
        'guichet'       => "#^\d{5}$#",
        'rib'           => "#^\d{2}$#",
        'code_banque'   => "#^\d{5}$#",
        'entier'        => "#^\d{0,}$#",
        'mailApsa'      => "#^[A-Z]+@apsaroke.(fr|com)$#",
        'code'          => "#^[a-zA-Z0-9]*$#",
        'majusculeTexte'=> "#^[A-Z0-9]*$#",
        //'code_four'     => "#^\d{11}$#",
        'iban'          => "#^[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}$#"
    );
    $GLOBALS['regex_champs'] = array(
        'MNEMONIC'          => 'mnemonique',
        'NOM'               => 'nom',
        'NOMJEUNEFILLE'     => 'jeune_fille',
        'PRENOM'            => 'nom',
        'ADRESSE'           => 'adresse',
        'ADRESSE2'          => 'commentaire',
        'CP'                => 'cp',
        'VILLE'             => 'nom',
        'TEL'               => 'telephone',
        'PRT'               => 'portable',
        'EMAIL'             => 'mail',
        'NSS'               => 'nss',
        'DTNAISSANCE'       => 'date',
        'LIEUNAISSANCE'     => 'nom',
        'NATIONALITE'       => 'nom',
        'DTENTREE'          => 'date',
        'DTDEPART'          => 'date',
        'STATUT'            => 'nom',
        'COEF'              => 'nombre',
        'TYPECONTRAT'       => 'nom',
        'TYPEHORAIRE'       => 'commentaire',
        'REMUNFIXE'         => 'nombre',
        'REMUNVAR'          => 'nombre',
        //'CDGUICHET'         => 'guichet',
        'NOMBANQUE'         => 'nom',
        //'CDBANQUE'          => 'code_banque',
        //'NUMCOMPTE'         => 'no_compte',
        'CLERIB'            => 'rib',
        'RIB'               => 'rib',
        'CMJC'              => 'nombre',
        'GSM'               => 'nombre',
        'PEE'               => 'nombre',
        'PRIME_ANCI'        => 'nombre',
        'PART_VARI'         => 'nombre',
        'EMAILAPSA'         => 'mailApsa',
        'DATECMDE'          => 'date',
        'DTDEBUT'           => 'date',
        'DTFINPREVUE'       => 'date',
        'NBJOURS'           => 'entier',
        'DETAIL'            => 'commentaire',
        'MONTFORFAIT'       => 'nombre',
        'COMMENTAIRE'       => 'commentaire',
        'TJM'               => 'nombre',
        'PA'                => 'nombre',
        'SUIVIPAR'          => 'nom',
        'CODE'              => 'code',
        'DTCREATION'        => 'date',
        //'FONCTION'          => 'entier',
        'ID'                => 'entier',
        'COMMISSION'        => 'nombre',
        'ACOMPTE'           => 'nombre',
        'PRIME'             => 'nombre',
        //'COMMENTAIRE'       => 'majusculeTexte',
        'COMMENTAIRE'       => 'commentaire',
        'com_general'       => 'majusculeTexte',
	'NUMCMDE'           => 'commentaire',
        'IBAN'              => 'iban',
        'BIC'               => 'no_compte',
        //'CODE_FOUR'         => 'entier',
        'CODE_FOUR'         => 'commentaire',
        'TITRE'             => 'commentaire',
	'CDE_BAN'           => 'guichet',
	'CDE_GUI'           => 'guichet',
	'NUM_CPT'           => 'no_compte',
	'STATUT'            => 'commentaire',
	'CODE_POSTAL'       => 'nombre',
	'RCS'               => 'nombre',
	'SIRET'             => 'nombre',
	'APE'               => 'code',
	'TVA_INTRA'         => 'code',
	'NOMD'              => 'commentaire',
	'LIBELLE'           => 'commentaire',
    );
    
    function test_champ($champ, $type) {
        $champ = str_replace("'", "`", $champ);
        if (preg_match($GLOBALS['regex_array'][$type], $champ)) {
            return true;
        }
        else {
            return false;
        }
    }
?>